### ISSUE TITLE
Exception in to_s(:line1) on some addresses

### ISSUE THREAD

**Issue by garyfoster** [derrek/street-address#27]
```
2.2.0 :017 > address = StreetAddress::US.parse("460 MALLARD AND PYE RD, ODUM, GA, 31555")
 => #<StreetAddress::US::Address:0x007f991a1228b0 @street="460 MALLARD", @street_type=nil, @suffix=nil, @prefix=nil, @city="ODUM", @state="GA", @postal_code="31555", @street2="PYE", @street_type2="Rd", @suffix2=nil, @prefix2=nil>
2.2.0 :018 > address.to_s(:line1)
TypeError: no implicit conversion of nil into String
	from /Users/garyfoster/.rvm/gems/ruby-2.2.0@smartpharmacy/gems/StreetAddress-1.0.6/lib/street_address.rb:886:in `+'
	from /Users/garyfoster/.rvm/gems/ruby-2.2.0@smartpharmacy/gems/StreetAddress-1.0.6/lib/street_address.rb:886:in `to_s'
```

**Comment by derrek** [comment]
You can try using github master branch.  I believe this is fixed.  I haven't released a gem yet of it as there's quite a bit of updates and I got busy with a new job :-(

**Comment by garyfoster** [comment]
confirmed, works in master, thanks
