### ISSUE TITLE
TypeError raised when accessing `line1`

### ISSUE THREAD

**Issue by backus** [derrek/street-address#31]
User address of this form

> 1234 B AND S DR, City Name CA

caused an exception when accessing line1:

```ruby
2.2.3 :006 > StreetAddress::US.parse('1234 B AND S DR, City Name CA').line1
TypeError: no implicit conversion of nil into String
	from /Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/StreetAddress-1.0.6/lib/street_address.rb:867:in `+'
	from /Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/StreetAddress-1.0.6/lib/street_address.rb:867:in `line1'
	from (irb):6
	from /Users/johnbackus/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'
```

I believe the operative part is '1234 B AND S'.  I think it is being parsed as an intersection when it shouldn't be?

**Comment by ngan** [comment]
We're seeing this issue as well.

**Comment by ngan** [comment]
Found a solution (kind of).  If you're know you're parsing an real address, use `parse_address` or `parse_informal_address` instead of `parse`.

**Comment by chamnap** [comment]
https://github.com/derrek/street-address/issues/27
